_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 3
                - 8
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.5
            "8":
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 1024
dnn_dropout:
    value: 0.5
epochs:
    value: 64
l2_reg_dnn:
    value: 0.001
l2_reg_embedding:
    value: 0.001
learning_rate:
    value: 0.001
